spring:
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product/**
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
        - id: cart-service
          uri: lb://CART-SERVICE
          predicates:
            - Path=/cart/**
        - id: comment-service
          uri: lb://COMMENT-SERVICE
          predicates:
            - Path=/comment/**
        - id: email-service
          uri: lb://EMAIL-SERVICE
          predicates:
            - Path=/email/**
        - id: jwt-service
          uri: lb://JWT-SERVICE
          predicates:
            - Path=/jwt/**
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
        - id: package-service
          uri: lb://PACKAGE-SERVICE
          predicates:
            - Path=/package/**

