spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: microservicio1
          uri: http://localhost:8081
          predicates:
            - Path=/microservicio1/**
          filters:
            - RewritePath=/microservicio1/(?<segment>.*), /${segment}

        - id: microservicio2
          uri: http://localhost:8082
          predicates:
            - Path=/microservicio2/**
          filters:
            - RewritePath=/microservicio2/(?<segment>.*), /${segment}

# Opcional: Configuraci√≥n de Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
