services:
  mysql-product:
    image: mysql:8.0
    container_name: mysql-product
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: product_service
    ports:
      - "3310:3306"
    volumes:
      - mysql-product-data:/var/lib/mysql
    networks:
      - spring-cloud-network

  mysql-user:
      image: mysql:8.0
      container_name: mysql-user
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: users_service
      ports:
        - "3307:3306"
      volumes:
        - mysql-user-data:/var/lib/mysql
      networks:
        - spring-cloud-network

  mysql-transaction:
    image: mysql:8.0
    container_name: mysql-transaction
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: transactions_service
    ports:
      - "3308:3306"
    volumes:
      - mysql-transaction-data:/var/lib/mysql

  mysql-cart:
    image: mysql:8.0
    container_name: mysql-cart
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cart_service
    ports:
      - "3309:3306"
    volumes:
      - mysql-cart-data:/var/lib/mysql

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - spring-cloud-network

  api-gateway:
      build: ./api-gateway
      container_name: api-gateway
      ports:
        - "8080:8080"
      environment:
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      depends_on:
        - eureka-server
      networks:
        - spring-cloud-network

  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "8085:8085"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-product:3306/product_service
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    depends_on:
      - mysql-product
      - eureka-server
    networks:
      - spring-cloud-network

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-user:3306/users_service
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    depends_on:
      - mysql-user
      - eureka-server

  transaction-service:
    build: ./transaction-service
    container_name: transaction-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-transaction:3306/transactions_service
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    depends_on:
      - mysql-transaction
      - eureka-server

  cart-service:
    build: ./cart-service
    container_name: cart-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-cart:3306/cart_service
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    depends_on:
      - mysql-cart
      - eureka-server


networks:
  spring-cloud-network:
    driver: bridge

volumes:
  mysql-product-data:
  mysql-user-data:
  mysql-transaction-data:
  mysql-cart-data:
