version: "3"

services:
  db:
    image: mysql:latest
    container_name: MySQL
    ports:
      - "8085:3310"
    environment:
      MySQL_ROOT_PASSWORD: "parcetamol"
    volumes:
      - ./schemas:/var/lib/mysql


