server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: microservicio1
          uri: lb://microservicio1
          predicates:
            - Path=/microservicio1/**
        - id: microservicio2
          uri: lb://microservicio2
          predicates:
            - Path=/microservicio2/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
